Feature/ot162 26
alkemyTech/OT162-React-client pull request #17
Opened 2022-03-22 15:02 UTC by CesarC87

Agregado Login con validaciones. Falta darle estilo

2022-03-25 03:04 UTC, GauntStrelok requested changes
Me gustaria ver evidencia de que esta funcionando

2022-03-25 03:04 UTC, GauntStrelok commented on src/Components/Auth/Login/Login.js
> +  }, [invalidPass]);
No estoy seguro que esto funcione de forma correcta

2022-03-25 03:04 UTC, GauntStrelok commented on src/Components/Auth/Login/Login.js
> +            fetch("http://localhost:3003/api/user/login", {
Esta request va a fallar, es algo que hiciste vos para probarlo?

2022-03-25 03:04 UTC, GauntStrelok commented
Tambien hacer un pull de main para arreglar conflictos

2022-03-25 16:00 UTC, CesarC87 commented on src/Components/Auth/Login/Login.js
> +            fetch("http://localhost:3003/api/user/login", {
Si si, porque es un Login que saque de otra app que habia hecho. Eso lo tengo que modificar, pero como es el componente que solo tiene que validar, lo deje asi por el momento

2022-03-25 16:02 UTC, CesarC87 commented on src/Components/Auth/Login/Login.js
> +  }, [invalidPass]);
![Untitled(1)(1)](https://user-images.githubusercontent.com/83318795/160157406-afc21828-886c-4b1f-a088-ceda866a93cb.png)

2022-03-25 16:06 UTC, CesarC87 commented on src/Components/Auth/Login/Login.js
> +  }, [invalidPass]);
El mensaje no se despliega ahora, tenés razon, pero es porque invalidPass todavia no esta seteado. Eso lo hace segun el response del fetch, pero como todavia no se hizo, está asi. Una vez que hagamos bien el fetch, se va a setear. Esta incidencia creo que pedia solo validar campos.

2022-03-30 05:25 UTC, GauntStrelok commented
Falta el pull de main para arreglar conflictos

2022-03-31 05:25 UTC, merged