Feature/ot162 34
alkemyTech/OT162-React-client pull request #28
Opened 2022-03-24 16:23 UTC by CesarC87

Terminado feature 34 --> Edicion de datos del sitio

2022-03-25 03:38 UTC, GauntStrelok requested changes
Falta evidencia en el PR, falta el link al ticket de JIRA, estan los cambios de otro branch tuyo en este branch, asi que vamos a primero mergear el branch de login antse que este,

2022-03-25 03:38 UTC, GauntStrelok commented on src/Components/SiteDataForm/SiteDataForm.js
> +  const { id } = useParams()
para que obtenes el id por useParams?

2022-03-25 03:38 UTC, GauntStrelok commented on src/Components/SiteDataForm/SiteDataForm.js
> +      {" "}
Sacale este espacio en blanco que no hace nada aca

2022-03-25 16:09 UTC, CesarC87 commented on src/Components/SiteDataForm/SiteDataForm.js
> +  const { id } = useParams()
Eso es lo que no entendi, porque segun la api habia que poner un id para hacer el put. Pero en teoria es solo 1 ong, no muchas, asique despues terminé harcodeando el id, le puse directamente 1, pero se ve que le deje el id params por las dudas que hubiera que hacerle algo

2022-03-25 16:12 UTC, CesarC87 commented on src/Components/SiteDataForm/SiteDataForm.js
> +  const { id } = useParams()
![imagen-20220324-162121](https://user-images.githubusercontent.com/83318795/160158961-375fb8cc-5695-48d9-b89b-c4e3e288d40b.png)

https://alkemy-labs.atlassian.net/browse/OT162-34

2022-03-25 16:13 UTC, CesarC87 commented on src/Components/SiteDataForm/SiteDataForm.js
> +      {" "}
Dale

2022-03-25 16:14 UTC, CesarC87 commented on src/Components/SiteDataForm/SiteDataForm.js
> +      {" "}
Listo

2022-03-31 05:43 UTC, GauntStrelok commented
Hacer uin nuevo pull de main para arreglar conflictos, e informarme por chat para poder darle prioridad al merge

2022-04-03 08:45 UTC, merged