Feature/ot162 61
alkemyTech/OT162-React-client pull request #56
Opened 2022-03-29 23:14 UTC by CesarC87

Finished feature 61 --> Displaying news table with its corresponding link to create/update news

![imagen](https://user-images.githubusercontent.com/83318795/160721504-a05d3cc5-3578-4cf2-bf66-1d948e6531e1.png)

2022-03-31 05:36 UTC, GauntStrelok requested changes

2022-03-31 05:36 UTC, GauntStrelok commented on src/Components/Table/Table.js
> +              {/* <TableCell align="right"><button onClick={() => eliminar()}>Editar</button></TableCell>
la eliminacion y la edicion dejarlos visibles en la tabla para que despues sea mas facil implementarlos

2022-03-31 05:36 UTC, GauntStrelok commented on src/Components/DataGrid/DataGrid.js
> +import * as React from 'react';
Si esta DataGrid ya no se usa, eliminar el componente

2022-04-02 15:37 UTC, CesarC87 commented
![imagen](https://user-images.githubusercontent.com/83318795/161390414-529ac98f-31cf-43df-b0b2-5eb70762feda.png)

Eliminado Datagrid

2022-04-03 08:47 UTC, GauntStrelok requested changes

2022-04-03 08:47 UTC, GauntStrelok commented on src/App.js
> +<<<<<<< HEAD
Esta mal mergeado el archivo, revisarlo y mergearlo bien

2022-04-03 17:47 UTC, CesarC87 commented
Ahi resolvi conflictos

2022-04-06 12:51 UTC, merged