Registration form/Parcial
alkemyTech/OT162-React-client pull request #7
Opened 2022-03-20 22:12 UTC by AngelMorales1

![Screenshot_1](https://user-images.githubusercontent.com/68304906/159188155-e32508aa-9fb1-4c50-a879-88907c1aa092.png)

Los campos del formulario de registro fueron agregados correctamente segun los requisitos pedidos, faltaria en un futuro agregar la peticion HTTP para subir los datos al backend y dar feedback de manera visual al usuario, de los distintos errores que pueden surjir durante la validacion.

2022-03-22 20:26 UTC, AngelMorales1 commented
> ![Screenshot_1](https://user-images.githubusercontent.com/68304906/159188155-e32508aa-9fb1-4c50-a879-88907c1aa092.png)
> 
> Los campos del formulario de registro fueron agregados correctamente segun los requisitos pedidos, faltaria en un futuro agregar la peticion HTTP para subir los datos al backend y dar feedback de manera visual al usuario, de los distintos errores que pueden surjir durante la validacion.

2022-03-25 02:46 UTC, GauntStrelok commented
Hacer pull de main para arreglar los conflictos

2022-03-31 05:40 UTC, GauntStrelok commented
Hacer un nuevo pull de main para arreglar conflictos, avisar por chat una vez arreglados para que le demos prioridad al merge este.

2022-04-03 08:42 UTC, GauntStrelok requested changes

2022-04-03 08:42 UTC, GauntStrelok commented on src/Services/privateApiService.js
> +<<<<<<< HEAD
Esta mal hecho el merge, revisarlo

2022-04-04 22:03 UTC, merged