Feature/ot162 85
alkemyTech/OT162-React-client pull request #82
Opened 2022-04-05 23:58 UTC by CesarC87

[Finished feature 85 ](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT162/boards/235?modal=detail&selectedIssue=OT162-85&assignee=6093e584afcdb7006934440a) --> Replaced routes with enviromental variables

Post:
![imagen](https://user-images.githubusercontent.com/83318795/161866869-622db764-b8a9-4579-aa6a-efcc361a8f97.png)
![imagen](https://user-images.githubusercontent.com/83318795/161866973-be1bdfc5-6885-4cd3-adf4-c3089a25d458.png)

Get:
![imagen](https://user-images.githubusercontent.com/83318795/161869967-6e229d35-b0d8-4cc2-b530-bf67f5d52413.png)

2022-04-07 13:27 UTC, GauntStrelok requested changes
Ademas hacer un nuevo pull de main para arreglar los conflictos

2022-04-07 13:27 UTC, GauntStrelok commented on .env.example
> +<<<<<<< HEAD
Esta mal mergeado, arreglar el merge

2022-04-07 13:27 UTC, GauntStrelok commented on src/Services/slideService.js
> +<<<<<<< HEAD
Esta mal mergeado, arreglar el merge

2022-04-08 06:12 UTC, GauntStrelok requested changes

2022-04-08 06:12 UTC, GauntStrelok commented on src/App.js
> +<<<<<<< HEAD
Cada vez esta peor el merge, si necesitas ayuda para resolverlo avisame

2022-04-08 06:12 UTC, GauntStrelok commented on src/Services/slideService.js
> +<<<<<<< HEAD
Sigue mal mergeado

2022-04-12 04:21 UTC, GauntStrelok requested changes

2022-04-12 04:21 UTC, GauntStrelok commented on src/Services/slideService.js
>  import axios from "axios";
Aun te falta arreglar este archivo

2022-04-12 12:14 UTC, CesarC87 commented
Listo, creo que ahi está

2022-04-14 04:21 UTC, merged